.PHONY: all clean

all: clock.exe

clock.exe: clock.c
	cc clock.c -o clock.exe -Wall -mwindows

clean:
	rm -f clock.exe
.PHONY: all clean

all: Clock.exe

Clock.exe: Clock.c
	$(CC) Clock.c -o Clock.exe -Wall -mwindows

clean:
	rm -f Clock.exe
