name: MSYS2 Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sys: [MINGW64, UCRT64,CLANG64,MINGW32]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        install: base-devel git
        pacboy: >-
          cc:p
    
    - name: Build
      shell: msys2 {0}
      run: |
        make
