name: Cross-Platform MinGW Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [i686, x86_64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
    
    - name: Build
      run: |
        make CC=${{ matrix.arch }}-w64-mingw32-gcc RC=${{ matrix.arch }}-w64-mingw32-windres

  macos-build:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]
    
    steps:
    - uses: actions/checkout@v4

    - name: Install MinGW
      run: |
        brew install mingw-w64
    
    - name: Build
      run: |
        make CC=${{ matrix.arch }}-w64-mingw32-gcc RC=${{ matrix.arch }}-w64-mingw32-windres
